### ISSUE TITLE
Cabling question

### ISSUE THREAD

**Issue by SBerg1980** [jensihnow/smarthome#3]
Unfortunately I can't see the wiring properly in the picture.

Are you supposed to cut the extension cable in half and then put both halves together both green kabels in 1 dupont?

**Comment by jensihnow** [comment]
Hi @SBerg1980,

You cut the cable to put the ESP as "man in the middle". It will read the button pushes and press electronically. There is no realy connection between the hand-set and the controller anymore. Therefore each wire has it's own dupont and it connected to a pin on the ESP.

Bests
Jens
